language: cpp
sudo: required
compiler:
  - gcc
before_install:
  - cat /etc/issue.net
  - sudo apt-get update
  - sudo apt-get install fp-compiler fp-units-gfx freeglut3 -y
script:
  - fpc -S2 spiral.dpr
notifications:
  email: false
