name: GitHub CI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y fp-compiler fp-units-gfx freeglut3
      - name: Build with FreePascal compiler
        run: |
          cd $GITHUB_WORKSPACE
          fpc -S2 spiral.dpr
